[theme]
base = "dark"
primaryColor = "#14B8A6"
backgroundColor = "#0B111E"
secondaryBackgroundColor = "#111C2E"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
